baseurl = "https://yzheng.me"
languageCode = "en-us"
theme = "hello-friend-ng"

[taxonomies]
  tag = "tags"
  category = "categories"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Yange's personal website"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  homeSubtitle = "currently a Student"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"
  
[author]
  name = "Yange Zheng"

[languages]
  [languages.en]
    title = "Yange Zheng"
    subtitle = "Yange's personal website"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"


# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blogs"
    name       = "Blog"
    url        = "/blogs"
    weight = 1

  [[menu.main]]
    identifier = "dejavu"
    name = "Déjà vu"
    url ="/dejavu"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name  = "Project"
    url = "/projects"
    weight = 3

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight = 4


    # Social icons
    [[params.social]]
    name = "email"
    url = "mailto:posterscofield@gmail.com"

    [[params.social]]
    name = "github"
    url = "https://github.com/camscofie/"